### ISSUE TITLE
Lapor

### ISSUE THREAD

**Issue by wibumoe** [LuckyIndraEfendi/AnimeIndo-Rest-API#3]
link stream ilang 
![anime-indo-rest-api vercel app_luckyanime_watch_anime_1873_oshi-no-ko_episode_5 - Google Chrome 24_12_2023 02_23_05](https://github.com/LuckyIndraEfendi/AnimeIndo-Rest-API/assets/131719695/cd71c74d-6542-4d55-a4d9-e8bcb614a71b)

**Comment by LuckyIndraEfendi** [comment]
sudah di fix ya, ada di updatean terbaru
